table transacoes
	lineageTag: 37e21c05-e152-41ec-a5f9-2ba3eb267ad0

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: 04e90652-bd15-4f0b-9b99-cf26153a3b93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			```
		displayFolder: Medidas
		lineageTag: 2800d9c4-b543-4d78-abb0-d060009b4cd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			) 
			```
		displayFolder: Medidas
		lineageTag: c24dcc44-e005-4d70-8439-ffe7db2f998f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		displayFolder: Colunas
		lineageTag: fa177673-6215-4b2e-a651-f16d5f0b4ccb
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: dd/mm/yyyy
		displayFolder: Colunas
		lineageTag: c77a96c2-f20c-4104-bcc0-0c56f5bc8b14
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: 375a186f-156c-4f6a-bd4f-911a5b205cc2
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: b50d19c8-d9f2-4d8d-8351-b95c19509afb
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: fatos
		source = ```
				let
				    source = Excel.Workbook(
				        File.Contents(base_transacoes), 
				        true, 
				        null
				    ),
				    
				    transacoes_Table = source{[Item="transacoes",Kind="Table"]}[Data],
				    
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

